export const GET_LIST_ITEMS = {
  START: "GET_LIST_ITEMS_START",
  CANCEL: "GET_LIST_ITEMS_CANCEL",
  ERROR: "GET_LIST_ITEMS_ERROR",
  SUCCESS: "GET_LIST_ITEMS_SUCCESS"
};

export const RESET = "RESET";
